### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by plantoschka** [lucavb/homebridge-esphome-ts#5]
I am getting the following items in the homebridge log:
```
[5/14/2020, 10:32:45 PM] [esphome] Bad Spiegel Licht Button discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Bad Spiegel Licht Relay discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] WC Spiegel Button discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] WC Spiegel Relay discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Luftentfeuchter Button discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Luftentfeuchter Strom discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Luftentfeuchter Current discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Luftentfeuchter Leistung discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Luftentfeuchter Relay discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Waschmaschine Button discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Waschmaschine Strom discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Waschmaschine Spannung discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Waschmaschine Leistung discovered and setup.
[5/14/2020, 10:32:45 PM] [esphome] Waschmaschine Relay discovered and setup.
```

I then try to blacklist the entries I don't need:
```
{
            "platform": "esphome",
            "devices": [
                {
                    "host": "badspiegellicht"
                },
                {
                    "host": "luftentfeuchter"
                },
                {
                    "host": "waschmaschine"
                },
                {
                    "host": "wc_esp"
                }
            ],
            "blacklist": [
                "Luftentfeuchter Current",
                "Luftentfeuchter Button",
                "Luftentfeuchter Strom",
                "Luftentfeuchter Leistung",
                "WC Spiegel Button",
                "Bad Spiegel Licht Button",
                "Waschmaschine Spannung",
                "Waschmaschine Button",
                "Waschmaschine Strom",
                "Waschmaschine Leistung"
            ]
        }
```

But they still appear in the Home App.

**Comment by lucavb** [comment]
So I just released beta 10 which should fix this issue. Could you please check?

**Comment by plantoschka** [comment]
Now the plugin doesn't work at all:

I always get the error message:
```
[5/16/2020, 11:41:56 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 734d2496-d14f-4794-940c-1a76dec5d542
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
```

When I remove the esphome entry from config homebridge starts fine.
I tried to remove my accessoires/ folder but the error still reappears.

**Comment by lucavb** [comment]
Alright beta 11 it is. Should be fixed now and I extended the debug logging.

**Comment by plantoschka** [comment]
Everything works now.
Thank you
